# Generated by Django 4.2.11 on 2024-05-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="vendor", name="id",),
        migrations.AlterField(
            model_name="vendor",
            name="average_response_time",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="fulfillment_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="on_time_delivery_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="quality_rating_avg",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_code",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
