# Generated by Django 4.2.11 on 2024-05-01 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_vendor_id_alter_vendor_average_response_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "po_number",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("order_date", models.DateTimeField()),
                ("delivery_date", models.DateTimeField(auto_now_add=True)),
                ("items", models.JSONField()),
                ("quantity", models.IntegerField()),
                ("status", models.CharField(max_length=100)),
                ("quality_rating", models.FloatField(default=0.0)),
                ("issue_date", models.DateTimeField()),
                ("acknowledgment_date", models.DateTimeField(null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.vendor"
                    ),
                ),
            ],
        ),
    ]
