# Generated by Django 4.2.11 on 2024-05-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_purchaseorder_delivery_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="quality_rating",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(default="ordered", max_length=100),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="average_response_time",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="fulfillment_rate",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="on_time_delivery_rate",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="quality_rating_avg",
            field=models.FloatField(null=True),
        ),
    ]
