# Generated by Django 4.2.11 on 2024-05-01 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_purchaseorder_issue_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("on_time_delivery_rate", models.FloatField(null=True)),
                ("quality_rating_avg", models.FloatField(null=True)),
                ("average_response_time", models.FloatField(null=True)),
                ("fulfillment_rate", models.FloatField(null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.vendor",
                    ),
                ),
            ],
        ),
    ]
